# https://www.mkdocs.org/user-guide/configuration/
# https://squidfunk.github.io/mkdocs-material/creating-your-site/#advanced-configuration

site_name: GHE Designer
repo_url: https://github.com/BETSRG/GHEDesigner
# site_url: https://github.com/BETSRG/GHEDesigner

theme:
  name: material

plugins:
  - search
  - schema_reader:
      include:
        - "ghedesigner/schemas/"
  - mkdocstrings:
      handlers:
        python:
          options:
            # https://mkdocstrings.github.io/griffe/reference/docstrings/
            docstring_style: sphinx
